### ISSUE TITLE
PWM permission issue Jetson AGX Xavier

### ISSUE THREAD

**Issue by lew221** [pjueon/JetsonGPIO#11]
Hi,

I am trying to use this library on Xavier. But even after copying the rules file and running in sudo, the permission to access PWM fails.
Other gpio function (Digital read write) seems to be working perfectly.

Same question have been asked here too:
https://stackoverflow.com/questions/64264667/gpio-permission-issue-nvidia-jetson-agx-xavier

Does anyone know what could be the problem?
Thanks

**Comment by pjueon** [comment]
Fixed the pwm issue
