### ISSUE TITLE
Using library

### ISSUE THREAD

**Issue by JesterFromLeicester** [pjueon/JetsonGPIO#14]
Hi,

I was planning to use your library on Jetson Xavier NX. I am wondering if you don't mind answering couple questions about it
I am aware that you need to add pin definitions for Xavier NX, in _gpio_pin_data.cpp_, and couple other bits in that file. Is there anything else to add?

Thanks

M

**Comment by alexisguiter** [comment]
Hi @JesterFromLeicester, I got my NX to work by simply following the changes on this page: https://github.com/pjueon/JetsonGPIO/pull/10/commits/e32d06454c9caf133b4ea6576502a64ca7da5028
