### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by yomuevans** [pjueon/JetsonGPIO#2]
cant compile for some reason. Here's the output to "g++ -o simple_out.cpp -lJetsonGPIO"

/usr/lib/gcc/aarch64-linux-gnu/7/../../../aarch64-linux-gnu/Scrt1.o: In function `_start':
(.text+0x18): undefined reference to `main'
(.text+0x1c): undefined reference to `main'
collect2: error: ld returned 1 exit status

**Comment by pjueon** [comment]
The -o flag is for the output file. You need to run something like this:
`g++ -o simple_out.out simple_out.cpp -lJetsonGPIO`
