### ISSUE TITLE
i2c multiplexer

### ISSUE THREAD

**Issue by spcrobocar** [pjueon/JetsonGPIO#35]
Can I use this library to control an i2c multiplexer, such as this one? https://www.adafruit.com/product/2717?gclid=Cj0KCQiA_c-OBhDFARIsAIFg3ezQ1yFYVWLO8nHYRgJTSH9le5aO6YkOjPbrBgCSSJ7OP47Hrzy64TEaArk6EALw_wcB

The background is this, I need to connect more than 2 devices to Jetson Xavier NX through i2c. For example, I need to connect Adafruit LED segment, LED matrix, and IMU. However, NX has only 2 i2c buses, I need the multiplexer.

**Comment by pjueon** [comment]
I'm afraid not. This library only supports simple input/output(high or low), input events, and pwm.
