### ISSUE TITLE
An error while using JetsonGPIO(C++) on Tx2 

### ISSUE THREAD

**Issue by kidxhac** [pjueon/JetsonGPIO#36]
I  followed the instruction and installed JetsonGPIO v1.0.3, however, when I ran the sample_out.cpp, there occured( other samples failed either):

### Aborted (core dumped)

Then I used JetsonGPIO in python (sample_out.py), it worked well and pin could output. Nothing changed between two conditions. Needs a little help, thanks.

**Comment by edge-ai4cv** [comment]
I have the same issue when I ran your "jetsongpio_test". The hardware is also Tx2 with Jetpack 4.6

**Comment by pjueon** [comment]
@kidxhac @edge-ai4cv 
Can you pull the `test_issue36`  branch  of this repository to your local repository and check if this fixes the issue?

**Comment by edge-ai4cv** [comment]
@pjueon 

It worked!  Thank you for your prompt fix!

**Comment by pjueon** [comment]
@edge-ai4cv Thanks for the confirmation. 

I just merge the branch to the master.

**Comment by kidxhac** [comment]
Sorry for the time difference. I pulled the newest master branch, it worked. Thank you.
