### ISSUE TITLE
Input Issue

### ISSUE THREAD

**Issue by lg93lggt** [pjueon/JetsonGPIO#4]
I have an issue, my input retvel always = -1855670792, but when I use python gpio it runs normally.

**Comment by sunfic** [comment]
I have similar issue. there is always big negative value

**Comment by rose-jinyang** [comment]
Hi
I have same issue.
Is there any solution?

**Comment by svins** [comment]
There is a bug. A return statement is missing from this line:
https://github.com/pjueon/JetsonGPIO/blob/0d305e0b149151de61f336d0d8a8ddf4725be7da/src/JetsonGPIO.cpp#L560

**Comment by MeijisIrlnd** [comment]
> 
> 
> There is a bug. A return statement is missing from this line:
> 
> https://github.com/pjueon/JetsonGPIO/blob/0d305e0b149151de61f336d0d8a8ddf4725be7da/src/JetsonGPIO.cpp#L560

yooo you just saved me hours of frustration thanks so much man
