### ISSUE TITLE
GPIO events triggered on modbus writes

### ISSUE THREAD

**Issue by yassiezar** [pjueon/JetsonGPIO#59]
I'm having a strange problem. We've connected 4 GPIOs as inputs to the Jetson board and configured interrupt event callbacks on each of them using a custom callback, as described in #25. We've also configured a modbus through 10.10.0.1:502 with libmodbus. 

The problem we ran into is that when a modbus write is performed, it triggers the GPIO events as well. These events seems to be random - sometimes none are triggered, sometimes all of them are triggered or anything in between. As far as I can tell, the modbus and epoll libraries used to trigger the GPIO events are not related at all. However, there seems to be some interaction somewhere. Since modmus and libmodbus are also included in the problem, I realise this is probably out of the scope for this repo, but I was wondering if you had some insight into what the issue may be or where I should start looking? 

I've also opened an issue on the (NVidia repo)]https://github.com/NVIDIA/jetson-gpio/issues/67]  (the same bug is observed with their Python library).

**Comment by pjueon** [comment]
Hmm.. Sorry, I have no idea. I don't even know what modbus is. 
Like you mentioned, it is probably out of the scope for this project.
Maybe you could get some insight from the Nvidia's repo, but I'm not sure.

All I can say is that check if your issue is really caused by modbus or not.
