### ISSUE TITLE
UDEV rules and Docker

### ISSUE THREAD

**Issue by automech-rb** [pjueon/JetsonGPIO#73]
Hi,

Do I need to update the UDEV rules (99-gpio.rules) on the Jetson before using this lib inside docker?
I am sorry if its already mentioned but I was not able to find it.

Thanks

**Comment by pjueon** [comment]
If you run the docker container with the root user permission, you don't need to install the udev rules to your host jetson device.

But if you want to run the container with the non-root user permission, you should install the udev rules to your jetson.

**Comment by automech-rb** [comment]
Got it. Thank you for the elaboration!
