### ISSUE TITLE
An issue on Jetson Xavier NX

### ISSUE THREAD

**Issue by rose-jinyang** [pjueon/JetsonGPIO#8]
Hello
How are you?
Thanks for contributing this project.
I've tried to use this library on Jetson Xavier NX but failed.
Could u add to support Xavier NX?
Thanks

**Comment by aditya-shriwastava** [comment]
Check [this](https://github.com/aditya-shriwastava/JetsonGPIO)

**Comment by rose-jinyang** [comment]
Thanks
I also added my cloned project to NX.
