### ISSUE TITLE
ChangeDutyCycle only accepts 1% increments

### ISSUE THREAD

**Issue by rogerartigaspursals** [pjueon/JetsonGPIO#9]
Hi.

I'm implementing the JetsonGPIO library on a Jetson Nano. My interest is on using few I/O and one of the PWM output. I'm checking the pin 33 PWM with this library and everything seems to work ok. By checking with an osciloscope, I'm ecountering the following issues:
1: the GPIO::PWM::ChangeDutyCycle is only accepting increments by 1%. If I command it with 0.1 value, there is no PWM output. At 0.5 value it starts to react, but the output is the same unit 1.0 is reached. The same happens with values between 1.0 to 2.0 and so on. By digging into the code, the ChangeDutyCycle functions seems to command down to nano-seconds and it seems that the math is correct. 

2: the output frequency  does not match the commanded frequency. For low values, such as 100, the output is correct, but as far as the commanded value increases, the output frequency is allways a little less. For instance, commanding 10.000 Hz is outputing 9987 Hz. 

I would like to have some insights to correct for both problems or at least to understand them, specially for point 1.

Many thanks to everybody answering.
Roger

**Comment by pjueon** [comment]
Sorry for the late response.

It might be the hardware limitation, but I'm not sure.
Unfortunately, I don't have any Jetson device to test right now so I can't offer you much information.

Did you try NVIDIA's official Jetson GPIO Python library ?
I believe the official python library set the pwm in the same way.

If you have same issue with the official python library too, you might ask some advice to the official github reposiory. (https://github.com/NVIDIA/jetson-gpio)
