### ISSUE TITLE
Adding Compat models for Jetson Orin 

### ISSUE THREAD

**Issue by anath93** [pjueon/JetsonGPIO#92]
compats_jetson_orins = (
    'nvidia,p3737-0000+p3701-0000',
    'nvidia,p3737-0000+p3701-0004',
    'nvidia,p3737-0000+p3701-0008',
    'nvidia,p3737-0000+p3701-0005',
    'nvidia,p3737-0000+p3701-0001',
)

**Comment by pjueon** [comment]
Thank you. I've just checked the official repo and your suggestion is correct: 
https://github.com/NVIDIA/jetson-gpio/commit/726e58d56eedb707a3c9bdfe6bb182bda298b315

Thank you very much for your contribution.
Could you make a PR for this? Then I'll merge it.

**Comment by anath93** [comment]
Yes I can do that by tomorrow.

**Comment by pjueon** [comment]
@anath93 
I merged your PR (#93). Thanks again!
Closing this issue.
